### ISSUE TITLE
Support --moduleResolution node16 in typescript

### ISSUE THREAD

**Issue by zkulbeda** [ivandotv/pumpit#38]
Hi! I'm really liking this library! Thank you for your work.
I use moduleResolution of node16 in my project, and can't import it without errors.
![image](https://user-images.githubusercontent.com/24959171/232150929-5fa0b34b-9571-4f5a-89a6-1c5dcf303c75.png)

Then I edit `package.json` in `node_modules`
```diff
...

  "umd:main": "./dist/prod/index.umd.js",
  "exports": {
    "require": "./dist/prod/index.cjs",
    "default": "./dist/prod/index.modern.js",
+   "types": "./src/index.ts"
  },
  "types": "./dist/types/index.d.ts",
...
```
But the source files is containing imports without .js extension, so there's other error

![image](https://user-images.githubusercontent.com/24959171/232152828-c99a1f69-f930-475b-98df-3381745260f1.png)

And last thing I tried is providing url to .d.ts file in `exports`:
```diff
...

  "umd:main": "./dist/prod/index.umd.js",
  "exports": {
    "require": "./dist/prod/index.cjs",
    "default": "./dist/prod/index.modern.js",
-   "types": "./src/index.ts"
+   "types": "./dist/types/index.d.ts"
  },
  "types": "./dist/types/index.d.ts",
...
```
But it also didn't work.
![image](https://user-images.githubusercontent.com/24959171/232153288-fd790554-f2f9-4709-a588-c14e60db1e4f.png)

Without extensions it just doesn't reexport types in `index.d.ts`

![image](https://user-images.githubusercontent.com/24959171/232154322-f4290d48-ba0c-41fa-806b-6086d608fe94.png)

I think the best solution for this problem is providing extensions for import paths and providing type's path to index.d.ts file in `exports`. What do you think?

**Comment by ivandotv** [comment]
can you create an example repository?

**Comment by ivandotv** [comment]
@zkulbeda this is now fixed
closed via: https://github.com/ivandotv/pumpit/pull/64
