### ISSUE TITLE
Hi does this library support aliasing like in Nest Js depedency injection

### ISSUE THREAD

**Issue by yousif-khalil-abdulkarim** [ivandotv/pumpit#44]
Hi does this library support aliasing like in Nest Js depedency injection
Link to [aliasing provider in nest js depedency injection](https://docs.nestjs.com/fundamentals/custom-providers#alias-providers-useexisting)

**Comment by ivandotv** [comment]
No, I don't see a need for aliasing dependencies. 
What is your usecase?
