### ISSUE TITLE
Dependency inversion principle in bindClass

### ISSUE THREAD

**Issue by David200197** [ivandotv/pumpit#47]
Hi, I am not very good with english, but i will try to express me. I am using this library with qwik.js because It does not support with decorators (for example, qwik.js with inversify.js). It is a very good library for this use case. the problem is that i use the SOLID principe "Dependency inversion principle" https://en.wikipedia.org/wiki/Dependency_inversion_principle and i need to use the bindClass's generic with interfaces, but it is not working. I am using my solution for this problem:

```ts
import type { BindKey, ClassOptions } from "pumpit";
import { PumpIt } from "pumpit";
import { UserRepository } from "./domain"
import { UserMongolRepository } from "./repository"

type Instanciable<T> =
  | { new (...arg: any[]): T }
  | { new (...arg: any[]): T; inject?: Inject };

type BindOptions<T> = Omit<
  Partial<
    ClassOptions<
      Instanciable<T>,
      "SINGLETON" | "TRANSIENT" | "REQUEST" | "CONTAINER_SINGLETON"
    >
  >,
  "type"
>;

class IoC extends PumpIt {
  bind = <T>(
    key: BindKey,
    value: Instanciable<T>,
    options?: BindOptions<T>
  ) => {
    return super.bindClass(key, value, options);
  };
}

export const container = new IoC();
container.bind<UserRepository>("TOKEN_REPOSITORY", UserMongoRepository);
```

can you add this features in your library? thanks for reading this

**Comment by ivandotv** [comment]
I'm not sure where the problem is, can you post the problem first? 
 Is this a `types` problem?

**Comment by David200197** [comment]
yes, in bindClass's Generic, i show you example

![image](https://github.com/ivandotv/pumpit/assets/80176604/8d39b03a-5718-4dd2-a615-fe23d1da202d)
``Type 'UserService' does not satisfy the constraint 'ClassValue'.``

this is UserService
```ts
import type { Maybe } from "~/core/libs/maybe";
import type { UsersEntity } from "./users.entity";
import type { UserEntity } from "./user.entity";

export interface UserService {
  findOne(id: string): Promise<Maybe<UserEntity>>;
  findAll(): Promise<UsersEntity>;
}
```
this is UserBaseService
```ts
import type { Maybe } from "~/core/libs/maybe";
import type { UserEntity } from "../models/user.entity";
import type { UserService } from "../models/user.service";
import type { UsersEntity } from "../models/users.entity";
import type { UserRepository } from "../models/user.repository";
import { USER_TOKEN } from "../di/tokens";
import type { Inject } from "~/core/models/inject";

export class UserBaseService implements UserService {
  static inject: Inject = [USER_TOKEN.REPOSITORY];

  constructor(private readonly userRepository: UserRepository) {}

  findOne = async (id: string): Promise<Maybe<UserEntity>> => {
    return await this.userRepository.findOne(id);
  };

  findAll = async (): Promise<UsersEntity> => {
    return await this.userRepository.findAll();
  };
}
```

**Comment by David200197** [comment]
You are right, for a common case, I do not require interfaces in bindClass, but I am using a Dependency inversion principle, and this allows me to switch between classes without affecting the original behavior, which allows me to scale my project without problems. I have got this idea from another project using inversify.js https://github.com/inversify/InversifyJS#step-1-declare-your-interfaces-and-types, and it seemed like a good idea to me being able to implement it with this library

**Comment by ivandotv** [comment]
There is no difference in what I gave you in the previous example and the example you posted from inversify.

**Comment by David200197** [comment]
oh excuse me, here is the example https://github.com/inversify/InversifyJS#step-3-create-and-configure-a-container, it puts interfaces to the bind generics to control which classes you pass through the arguments of the bind method. If there is something you don´t quite understand, feel free to tell me ´cause my english isn´t pretty good

**Comment by ivandotv** [comment]
Can you write me an example with `pumpit` that doesn't work?

**Comment by David200197** [comment]
I show a simple example
```ts
interface Vehicle {
     run(): void
}
class Car implements Vehicle {
    run(){
        console.log("the car is running")
    }
}

class Motorcycle implements Vehicle {
    run(){
        console.log("the motorcycle is running")
    }
}

const container = new PumpIt()
//case 1
container.bindClass<Vehicle>("VEHICLE", Car) // error: Type 'UserService' does not satisfy the constraint 'ClassValue'.

//case 2: I change Car to Motorcycle
container.bindClass<Vehicle>("VEHICLE", Motorcycle) // error: Type 'UserService' does not satisfy the constraint 'ClassValue'.
```

**Comment by ivandotv** [comment]
`bindClass` method is not generic.
https://github.com/ivandotv/pumpit#registering-classes

**Comment by David200197** [comment]
oh I understand. I needed it to be generic to comply with the dependency inversion principle, and although I extended PumpIt Class to be able to use it, it seemed like a good idea to me for it to be in the original library, since it seems to me like a very good library for cases where there is incompatibility with the decorators

**Comment by David200197** [comment]
If you want, I can fork the project and add the generic to bindClass to make it more adaptable

**Comment by ivandotv** [comment]
There is no reason for `bindClass` to be generic.
