### ISSUE TITLE
Async factory

### ISSUE THREAD

**Issue by Jess182** [ivandotv/pumpit#95]
Is it possible to set async factory to return fulfilled promise? because when i log provider it still as a promise

```ts
container.bindFactory('DenoKV', () => {
	return Deno.openKv(Deno.env.get('DENO_KV_URL'));
}, { scope: SCOPE.SINGLETON });
```
![image](https://github.com/user-attachments/assets/78e661cb-a452-4130-aa45-9380ae34a4a5)

**Comment by ivandotv** [comment]
I thought about creating `async` resolvers but eventually decided against it, because it would add a lot of complexity to the code base, and the file size would increase (I want to keep the file size low, so the package can be used for front end)

What you can do it resolve the value , and then `await` it
```ts
const myPromise = container.resolve('DenoKV')
await myPromise
// use promise result here
```

**Comment by Jess182** [comment]
Yes, I did a workaround since the provider receives it through the constructor
```ts
constructor(private client: Deno.Kv) {
		if ('then' in client) {
			(client as any).then((result: Deno.Kv) => this.client = result);
		}
	}
```
However there are times when due to asynchronicity when some method uses the provider, it has not yet been "resolved"

But I appreciate the response and the clarification, cheers

**Comment by ivandotv** [comment]
FYI, you should not use `async` in your constructors.

`this.client` can still be a `promise` when you try to access it.

```ts
const yourClass = new Class()
yourClass.client // this is a promise
```

**Comment by Jess182** [comment]
That's correct, that's why my initial question was if there was a way for the ioc container to have async factories
